### ISSUE TITLE
Small suggestion for reproducibility

### ISSUE THREAD

**Issue by khughitt** [che625/olson-ms-nb#5]
Nice work! It is very refreshing to see such a clear documentation of analysis.

Just had a couple small suggestions that you may include if you wish:

1. Print out version info for all software used. In some cases this is already clear, but It can help to include a chunk at the end where you spit out the versions for R, Python, Linux, etc. along with an R call to `sessionInfo()`.
2. If you want to make it easier to view the notebook, you can include a link to nbviewer in your README, e.g.:

[View analysis](http://nbviewer.ipython.org/github/che625/olson-ms-nb/blob/1.0/BiGo_dev.ipynb)

Cheers,
Keith

**Comment by sr320** [comment]
@khughitt Thanks for taking the time to take a look at this and provide suggestions! Version numbers and nbviewer link has now been included in [readme](https://github.com/che625/olson-ms-nb/blob/master/README.md)

Thanks 
Steven
